---
title: "Experimental Design"
bibliography: references.bib
biblio-style: apalike
link-citations: yes
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
---


```{r setup, include=FALSE}
source('assets/setup.R')

# knitr::opts_chunk$set(cache = TRUE)
set.seed(1)
```

This video provides an overview of typical designs used in psychology experiments.

:::lo
**LEARNING OBJECTIVES**

1. Understand the structure of common experimental designs in psychology
1. Understand the relative advantages and disadvantages of common experimental designs in psychology

:::


# Video
`r qbegin(1)`
How do you turn an idea for an experiment into a practical design?

You can find the answer after the video


`r qend()`



Psychology studies often follow common design principles that have worked well in past experiments. In this video, we will discuss some of the more popular experimental designs and compare their relative advantages and disadvantages. 

Contact for questions and comments: [aba.szollosi@ed.ac.uk](aba.szollosi@ed.ac.uk)



<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2010292/sp/201029200/embedIframeJs/uiconf_id/32599141/partner_id/2010292?iframeembed=true&playerId=kaltura_player&entry_id=1_4v4qf6hz&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_zlhykxzj" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>

Download the slides for this presentation [here](Slides/Design2Design.pdf).

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`
Early-stage scientists are often tempted to design entirely novel experiments to answer their research questions. But you'll get a lot more support - and make a lot more progress - if you build on the work of others. Think about some successful experimental designs that have been used before, and try to construct your new experiment based on those principles.

`r solend()`

# Quiz

`r qbegin(2)`
Repeated measures designs allow us to collect more data from fewer participants. Why not use this design exclusively?
`r qend()`

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`
Among other reasons, repeated measures designs are subject to potential order effects, which can be mitigated but cannot be fully avoided. More generally, various experimental designs have both advantages and disadvantages – choosing a specific one always comes with trade-offs.
`r solend()`

`r qbegin(2)`
Can experimental designs be mixed?
`r qend()`

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`
Yes. The choice of an experimental design always depends on the research question at hand, and it often makes sense to combine various designs. The designs we considered in this video can serve as useful starting points.
`r solend()`


<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>