---
title: "Research Ethics & GDPR"
bibliography: references.bib
biblio-style: apalike
link-citations: yes
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
---


```{r setup, include=FALSE}
source('assets/setup.R')

# knitr::opts_chunk$set(cache = TRUE)
set.seed(1)
```

This video outlines the key features of the General Data Protection Regulations, and how it influence the conduct of modern research.

:::lo
**LEARNING OBJECTIVES**

1. Explain what GDPR is. 
1. Understand how GDPR classifies data. 
1. Be aware of how to appropriately store and process data under GDPR.
:::


# Video
`r qbegin(1)`
Before watching the video, consider this question. GDPR regulations note three kinds of data:  

- Data
- Personal Data
- Sensitive Personal Data

Why do you think these legal regulations attribute some data to be more personal than others, and some data to be more sensitive than others? And why might these different types of data require different types of protection?

You can find answers after the video

`r qend()`



The General Data Protection Regulations, or GDPR, are a set of European Union and UK rules that define how we collect, store and process human data. Abiding by these regulations, in order to protect rights like privacy, is an important component of any research plan. In this video, we introduce GDPR, and discuss some strategies for ensuring that you stay within permissable uses of data. You can follow along the video using the slides below. For questions and comments, contact [hugh.rabagliati@ed.ac.uk](hugh.rabagliati@ed.ac.uk).


<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2010292/sp/201029200/embedIframeJs/uiconf_id/32599141/partner_id/2010292?iframeembed=true&playerId=kaltura_player&entry_id=1_u880ffib&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_95p2xq1l" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>

`r knitr::include_url('Slides/02_gdpr_lecture.html')`

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`
Under the jurisdiction of GDPR, any information collected about another human can be considered data. Personal Data dsecribes information that can be used to identify another individual. This could be a name, an address, a picture, a video, a voice recording, an online alias, or more. EEG data, for instance, can be identifying, and thus counts as personal data. Sensitive personal data is information that not only identifies an individual, but highlights special information about them that could potentially be harmful if made widely available. This include information such as racial or ethnic origin, political opinions, or religious beliefs, as well as genetic and biometric data.

These different types of data require different treatments because of the potential harm they could cause if made publicly available. Consider, if you put online an anonymised dataset of accuracy in a memory task, then there would be no perceivable risk to the research subjects. But if you included the research subjects' personal information, then there is a risk that the research subjects' privacy might be invaded. And if you included their ethnicity or political orientation as well, then there significant additional risks. Thus, the different types of data require different treatments.

`r solend()`

# Quiz

`r qbegin(2)`
Why is it important to store gathered personal data on University of Edinburgh servers?
`r qend()`

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`

University of Edinburgh servers have a high degree of security - if you password protect your data appropriately, then there should be little danger of personal data being accessed outside of your research team. In addition, University of Edinburgh servers are guaranteed to be hosted in GDPR-compliant locations. This is important, because moving personal data outside of a GDPR compliant location presents significant risks. By contrast, your personal storage accounts from private companies may not offer this guarantee. 
`r solend()`




<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>