---
title: "Principles-based Ethical Research"
bibliography: references.bib
biblio-style: apalike
link-citations: yes
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
---


```{r setup, include=FALSE}
source('assets/setup.R')

# knitr::opts_chunk$set(cache = TRUE)
set.seed(1)
```


:::lo
**LEARNING OBJECTIVES**

1. Understand the principles-based approach to ethical research.
1. Understand the different ethical approaches used in different research environments.
:::

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2010292/sp/201029200/embedIframeJs/uiconf_id/32599141/partner_id/2010292?iframeembed=true&playerId=kaltura_player&entry_id=1_zpyz9qul&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_odcydj07" width="640" height="456" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>

# Basic terminology

`r qbegin(1)`
In the context of research ethics, what do you think the following concepts mean?

- *Scientific value*
- *Respect for persons*
- *Personal autonomy*
- *Social Responsibility*

`r qend()`

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`
| Term | Definition |
|:-----|:-----------|
|*Scientific value* | ANSWER HERE. |
|*Respect for persons* | ANSWER HERE. |
|*Personal autonomy* | ANSWER HERE. |
|*Social Responsibility* | ANSWER HERE |

`r solend()`

# Ethical Principles

Concepts like *scientific value* and *social responsibility* play important roles as ethical principles that guide our research. They help researchers to decide upon the types of questions they can ask, and how to answer those questions. In this video, we discuss the ethical systems that psychologists use to guide their research. You can also follow along the video using the slides below.

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2010292/sp/201029200/embedIframeJs/uiconf_id/32599141/partner_id/2010292?iframeembed=true&playerId=kaltura_player&entry_id=1_tah62qmr&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_e3nxqmeq" width="640" height="456" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>

** SLIDES GO HERE **

`r knitr::include_url('file:///Users/hugh/GitHub/ResearchSkills/TestLab/ethics_lecture/01_principles_lecture.html')`

# Quiz 1

`r qbegin(2)`
SETUP FOR THE QUESTION

- PART 1 OF THE QUESTION
- PART 2 OF THE QUESTION
- PART 3 OF THE QUESTION

`r qend()`

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`
BACKGROUND TO THE SOLUTION

- SOLUTION TO PART 1
- SOLUTION TO PART 2
- SOLUTION TO PART 3

`r solend()`



# References

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>