---
title: 'Welcome to Practical Research Skills'
output: 
  bookdown::html_document2:
    toc: false
---

Welcome to Practical Research Skills, a workbook created by staff and students at the University of Edinburgh's School of Philosophy, Psychology and Language Sciences. This resource aims to support our undergraduates in carrying out their first research projects. Using the menu above, you can find a set of videos and practical materials that provide a knowledge base for how to get research done. From coming up with a research design to applying for ethical review, this resource will teach you how to be a psychological scientist.

### How to use this material

This course and workbook contain a range of chapters on some of the stages in crafting a research project. For more details, take a watch of this video.

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2010292/sp/201029200/embedIframeJs/uiconf_id/32599141/partner_id/2010292?iframeembed=true&playerId=kaltura_player&entry_id=1_j35277yv&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_t4vlhr55" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>

**Note:** The material in this workbook will be expanded through the 2021/22 academic year. When new content is added, you will be sent notifications on Learn.

For questions, contact [Hugh Rabagliati](hugh.rabagliati@ed.ac.uk).



