---
title: "Constructing a Hypothesis"
bibliography: references.bib
biblio-style: apalike
link-citations: yes
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
---


```{r setup, include=FALSE}
source('assets/setup.R')

# knitr::opts_chunk$set(cache = TRUE)
set.seed(1)
```

This video, the first of a series of three recordings focused on research design, discusses the importance of formulating the hypothesis correctly. 

:::lo
**LEARNING OBJECTIVES**

You will learn how to operationalise your research question into an informative and falsifiable hypothesis, which will give focus and clarity to your subsequent research efforts. Through this, you will also have an opportunity to reflect on how this aspect of research design is founded upon the philosophical discipline of logic, through the use of “if-then” conditionals.
:::


# Video 

`r qbegin(1)`
To get you thinking about this, ask yourself “What makes a good hypothesis?” Think about the predictions from a paper you’ve recently read – could you evaluate their quality, or do you feel you currently lack the ability to do so? Once you mulled over this, have a look at the video!
You can find some answers after the video

`r qend()`

This is the first in a series of three videos on how to design research. Each video highlights the importance of a key activity that may under normal circumstances receive less reflection than necessary. These videos also include exercises that ask you to analyse hypotheses from a paper you’ve recently read. The first one is about the importance of formulating the hypothesis in the most optimal way possible. The videos are made by Dr Jasna Martinovic, senior lecturer in Psychology. Jasna does research on visual perception and visual neuroscience, mainly focusing on colour vision and cognition. 


Contact: [J.Martinovic@ed.ac.uk](J.Martinovic@ed.ac.uk) 

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2010292/sp/201029200/embedIframeJs/uiconf_id/32599141/partner_id/2010292?iframeembed=true&playerId=kaltura_player&entry_id=1_8xp0wyvc&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_rg2dj0wa" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>


Download the slides for this presentation [here](Slides/Question_01_Constructing.pdf).

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`
What makes a good hypothesis? First, it should be possible to disprove it, rather than just to confirm it or to end up with inconclusive evidence. Second, it should generalise to a broader set of real-world phenomena, rather than being limited to a set of pre-determined conditions under which it is evaluated in the study.


`r solend()`

# Quiz

Here’s a few questions to test your knowledge after watching this video.

`r qbegin(2)`
Q. What is the link between a good hypothesis and a good theory?

`r qend()`

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`

A good theory makes clear, non-trivial and testable predictions – such a theory can easily be translated into useful research hypotheses.

`r solend()`

`r qbegin(3)`
Q. How do we construct a good hypothesis?

`r qend()`

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`

 To make a prediction as clear as possible, it is best to formulate it in a conditional “if-then” statement. Such sentences can then be made to be as informative as possible, by extending the “if-then” parts with further conditions to which our prediction should apply.
 
`r solend()`


<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>