---
title: "Testing a Hypothesis"
bibliography: references.bib
biblio-style: apalike
link-citations: yes
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
---


```{r setup, include=FALSE}
source('assets/setup.R')

# knitr::opts_chunk$set(cache = TRUE)
set.seed(1)
```

This video, the second of a series of three recordings focused on research design, discusses the process of hypothesis testing. 

:::lo
**LEARNING OBJECTIVES**

You will learn how to translate a conceptual hypothesis, stated in the terminology of theoretical constructs, into a set of relations between empirical factors and variables that can be evaluated using statistics. Understanding that conceptual predictions can be mapped onto empirical variables and statistical procedures in multiple ways will give you an insight into why it is important to have mastery of multiple experimental and analytical methods.
:::


# Video 

`r qbegin(1)`
To get you thinking about this, ask yourself if you’ve ever been confused about the “null-hypothesis” and wondered how it relates to the empirical hypothesis about relations between variables made in a study. Is the null hypothesis directly related to our conceptual hypothesis? If not, how should we think of it and do we need to explicitly mention in our study’s results that we tested the null-hypothesis? Once you mulled over this, have a look at the video!
You can find some answers after the video

`r qend()`

This is the second in a series of three videos on how to design research. Each video highlights the importance of a key activity that may under normal circumstances receive less reflection than necessary. The second video disambiguates the role of conceptual, empirical and statistical hypotheses the process of hypothesis testing. Within, there is an exercise that ask you to analyse hypotheses from a paper you’ve recently read – ideally, this will be the same paper you used for the exercises in the first video. The author of these videos is Dr Jasna Martinovic, senior lecturer in Psychology. Jasna does research on visual perception and neuroscience, mainly focusing on colour vision and cognition. 

Contact: [J.Martinovic@ed.ac.uk](J.Martinovic@ed.ac.uk) 

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2010292/sp/201029200/embedIframeJs/uiconf_id/32599141/partner_id/2010292?iframeembed=true&playerId=kaltura_player&entry_id=1_9fzbk3sh&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_kv1cxitf" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>

Download the slides for this presentation [here](Slides/Question_02_Testing.pdf).

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`
What is a null-hypothesis? The null hypothesis belongs to the domain of inferential probabilistic statistics – in a statistical test, this is the default assumption that the values belonging to two populations of responses only differ due to sampling error. When there is sufficient evidence to the contrary, i.e. the p value is sufficiently low to indicate that this default assumption is very unlikely, we reject the null hypothesis. So, a null hypothesis is only relevant from a statistical point of view and does not relate to your conceptual or empirical predictions. There is no need to state it within your hypothesis section, e.g. that you predicted that word familiarity should correlate with its likelihood of being recalled, and that the null hypothesis states that this would not be true. If you write this, you’re mixing up concepts belonging to two different levels – empirical and statistical – which is less than ideal.

`r solend()`

# Quiz

Here’s a few questions to test your knowledge after watching this video.

`r qbegin(2)`
Q. How does precision of a hypothesis relate to its informativeness? 

`r qend()`

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`

More precise hypotheses are more informative because they provide additional detail about the presumed relationship between empirical variables. Rather than just stating that process A relates to process B, we should strive to explain a directional relation (e.g. A causes B), specify how strong the link (i.e. effect size) between A and B is, and ultimately, characterise mathematically how changes in A predict changes in B. The mathematical explanation is the golden standard in physics, but is more elusive in humanities and social sciences due to the complexity of studied phenomena and subsequent difficulties in quantifying them. 
`r solend()`

`r qbegin(3)`
Q.	Why is it good for a psychologist to master multiple research and analytic techniques?
`r qend()`

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`

A conceptual hypothesis can be translated into an empirical hypothesis in many ways, depending on the variables we choose to manipulate (i.e. independent variables) and their outcomes we intend to measure (i.e. dependent variables). Also, multiple statistical approaches can be applied to empirical data. A researcher who has a broader toolkit of skills will be able to design a study that can capture the studied phenomena in a most precise, informative fashion. 
`r solend()`


<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>