---
title: "Reviewing the Literature"
bibliography: references.bib
biblio-style: apalike
link-citations: yes
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
---


```{r setup, include=FALSE}
source('assets/setup.R')

# knitr::opts_chunk$set(cache = TRUE)
set.seed(1)
```

This video, the third in a series of three recordings focused on research design, discusses the importance of a thorough literature review for conducting a successful research project. 

:::lo
**LEARNING OBJECTIVES**

You will learn some practical tips on how to conduct literature reviews. You will also be able to re-evaluate the process of formulating a hypothesis, which was covered in the first video, and understand how it is informed and refined by knowledge of theories and methodologies relevant to previous work in the field.
:::


# Video 

`r qbegin(1)`
To get you thinking about this, ask yourself: What are the possible pitfalls of designing and conducting a research project after thoroughly reading only one or two articles? Think of all the things that could be less than optimal with your hypothesis and your research methods, and how this might consequently impact on the conclusions you could make from your results.
You can find some answers after the video

`r qend()`

This is the third and final of the series of videos on how to design research. Each video highlights the importance of a key activity that may under normal circumstances receive less reflection than necessary. Here, the core skill of literature reviewing is discussed. The video is made by Dr Jasna Martinovic, senior lecturer in Psychology. Jasna does research on visual perception and visual neuroscience, mainly focusing on colour vision and cognition. 

Contact: [J.Martinovic@ed.ac.uk](J.Martinovic@ed.ac.uk) 

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2010292/sp/201029200/embedIframeJs/uiconf_id/32599141/partner_id/2010292?iframeembed=true&playerId=kaltura_player&entry_id=1_oj82j20u&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_8d4wr09v" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>

Download the slides for this presentation [here](Slides/Question_03_Reviewing.pdf).

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`
If I designed and conducted a research project without doing a thorough literature review, I would run into a series of problems. I could be unaware of different theoretical models that would make opposite predictions, and that I should put to the test if my study is to be as informative as possible.  I could lack knowledge of inadequacies of my methods in answering these sets of questions if I fail to read work that relies on different research techniques. I could be missing out important independent variables that should be included in the design or at least controlled for. Finally, I could be using suboptimal statistical tools to evaluate my empirical predictions. All these problems would mean that even if the results are in line with my predictions, others would be able to question them and would rightly request me to discuss these inadequacies extensively. It is always good to devote a part of your discussion to limitations and future directions, but it is even better to be able to do so after making at least some firm conclusions. A thorough literature review helps us to do that by helping us design our study in the best possible way.

`r solend()`

# Quiz

Here’s a question to test your knowledge after watching this video.

`r qbegin(2)`
Q. What is the purpose of a literature review?

`r qend()`

`r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)`

The purpose of a literature review is twofold: to get up to speed with the state-of-the-art (i.e. the best understanding of the research area at this time) and to understand the skillset required to conduct and understand research in this area.  A thorough review allows you to pick up previous research approaches that one can use as a starting point and evaluate the theoretical models and hypotheses regarding the phenomenon in question, as well as research methods used to test those predictions.
`r solend()`


<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>