---
title: "Signposts in Research Articles"
bibliography: references.bib
biblio-style: apalike
link-citations: yes
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
---


```{r setup, include=FALSE}
source('assets/setup.R')

# knitr::opts_chunk$set(cache = TRUE)
set.seed(1)
```


:::lo
**LEARNING OBJECTIVES**

1. Focus on the signposts that highlight an article's structure

:::

** Discovering signposts **

Go back to the article you skimmed, and highlight those words that *sign post* what the authors want to communicate. Sign post words are words that give structure, like:

*because, since, given this argument, thus, therefore, hence, it follows that, consequently, nevertheless, however, but, in the first case, on the other hand*

These are signposts which help you keep track of the structure of the introduction and discussion.

Here is an example of how a writer might use these words to build a skeleton for an article: 

*The literature suggests that ... *[claim goes here]. *This suggestion generates at least two open questions. First... *[question 1 goes here]*. Second... *[question 2 goes here]*. However other research gives us reason to question these earlier results, generating contrasting questions... *[contrasting questions go here]*. These conflicting points therefore motivate our studies...*[description of studies go here]

The words “suggest” and “however” and “motivate” make it easy to see where the argument is going. The writer is introducing one claim, and explaining what its implications are. Then, they introduce reasons to doubt that claim. The contrast between the initial proposal and the contrasting claim is the motivation that the writer is using to put forward their studies. You’ll want to put signposts like these in your own writing, to explain why you did the studies that you performed..


<!-- # Video -->
<!-- `r qbegin(1)` -->
<!-- Part of scientists’ job is to find out when their explanations are wrong. How do you think experiments can help them achieve this aim? -->

<!-- You can find the answer after the video -->


<!-- `r qend()` -->


<!-- Experiments make a frequent appearance in contemporary psychological science. In this video, we discuss why they are important and what we can learn from them. We will illustrate the answers to these questions with the Stroop task. -->

<!-- This video is presented by Aba Szollosi, who is a postdoctoral researcher in Psychology. Contact: [aba.szollosi@ed.ac.uk](aba.szollosi@ed.ac.uk ) -->



<!-- <iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2010292/sp/201029200/embedIframeJs/uiconf_id/32599141/partner_id/2010292?iframeembed=true&playerId=kaltura_player&entry_id=1_rvxb3oxy&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_v1xotko3" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe> -->

<!-- Download the slides for this presentation [here](Slides/Design1Introduction.pdf). -->

<!-- `r solbegin(show = params$SHOW_SOLS, toggle = params$TOGGLE)` -->
<!-- Experiments can help us achieve this aim by providing tests for our explanations. If the results are not what we expected, we know that there is a problem with our explanation. -->

<!-- `r solend()` -->


<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>